export const ADD_PRODUCT_STORE = "ADD_PRODUCT_STORE";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const CHANGE_PRICE = "CHANGE_PRICE";
